name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * 0'  # Weekly security scan

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-Dwarnings"

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
      - uses: Swatinem/rust-cache@v2
      
      # Code formatting
      - name: Check formatting
        run: cargo fmt --all -- --check
      
      # Linting
      - name: Run clippy
        run: cargo clippy --all-targets --all-features -- -D warnings

  test:
    name: Test
    needs: check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      
      # Run tests with coverage
      - name: Install cargo-tarpaulin
        run: cargo install cargo-tarpaulin
      
      - name: Run tests with coverage
        run: cargo tarpaulin --ignore-tests --out Xml
      
      # Upload coverage report
      - name: Upload coverage
        uses: codecov/codecov-action@v3

  security:
    name: Security audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      # Run security audit
      - uses: actions-rs/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  dependency-check:
    name: Check dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      # Check for outdated dependencies
      - name: Install cargo-outdated
        run: cargo install cargo-outdated
      
      - name: Check outdated dependencies
        run: cargo outdated -R

  build:
    name: Build
    needs: [test, security]
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            artifact_name: geneuron
            asset_name: geneuron-linux-amd64
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            artifact_name: geneuron.exe
            asset_name: geneuron-windows-amd64.exe
          - os: macos-latest
            target: x86_64-apple-darwin
            artifact_name: geneuron
            asset_name: geneuron-macos-amd64
          - os: ubuntu-latest
            target: wasm32-unknown-unknown
            artifact_name: geneuron.wasm
            asset_name: geneuron-web.wasm

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Install Linux Dependencies
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libasound2-dev libudev-dev pkg-config

      - name: Build Binary
        run: cargo build --release --target ${{ matrix.target }}

      - name: Prepare Web Assets
        if: matrix.target == 'wasm32-unknown-unknown'
        run: |
          mkdir -p dist
          cp index.html dist/
          cp target/wasm32-unknown-unknown/release/geneuron.wasm dist/

      - name: Upload Binary
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.asset_name }}
          path: |
            target/${{ matrix.target }}/release/${{ matrix.artifact_name }}
            dist/*
          if-no-files-found: error

  create-release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/download-artifact@v3

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            geneuron-linux-amd64/geneuron
            geneuron-windows-amd64.exe/geneuron.exe
            geneuron-macos-amd64/geneuron
            geneuron-web.wasm/dist/*
          draft: true
          prerelease: false
          generate_release_notes: true

  deploy-docs:
    name: Deploy Documentation
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3
      
      - name: Build documentation
        run: cargo doc --no-deps --all-features
      
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/doc
          force_orphan: true